notifications:
  on_success: never
dist: xenial
sudo: false
language: ruby
rvm:
  - 2.4.5
  - 2.5.3
  - 2.6.0
  - ruby-head
before_install:
  - gem install bundler --no-document -v 1.17.3
script: bundle exec rubocop
